---
image: quay.io/ansible/molecule:3.2.0a0

services:
  - docker:dind

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

molecule:
  tags:
    - docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    - molecule test
