---
image: docker:19.03.0

services:
  - docker:19.03.0-dind

stages:
  - lint
  - test

yamllint:
  stage: lint
  before_script:
    - pip install yamllint
  script:
    - yamllint .

ansible-lint:
  stage: lint
  before_script:
    - pip install ansible-lint
  script:
    - ansible-lint

tox:
  stage: test
  before_script:
    - pip install tox
  script:
    - tox
